### ISSUE TITLE
java.lang.AbstractMethodError with latest Google Maps library

### ISSUE THREAD

**Issue by ultimate-tester** [mg6maciej/android-maps-extensions#41] opened 2016-08-26 19:12 UTC
If I use 'com.google.android.gms:play-services:9.4.0' the project will not run. The following exception will be thrown:

```
java.lang.AbstractMethodError: abstract method "com.google.android.gms.maps.GoogleMap com.androidmapsextensions.MapHolder$Delegate.getMap()"
            at com.androidmapsextensions.MapHolder.getExtendedMap(MapHolder.java:27)
            at com.androidmapsextensions.SupportMapFragment.getExtendedMap(SupportMapFragment.java:44)
```

Using an older version like 'com.google.android.gms:play-services:3.2.65' it runs fine.

**Comment by ultimate-tester** [comment] 2016-08-26 19:23
Same thing happens when using 'com.google.android.gms:play-services-maps:9.4.0' instead of an older version like 'com.google.android.gms:play-services-maps:8.1.0'

**Comment by mitjakoren** [comment] 2016-08-27 07:00
I can confirm the same behavior as from @ultimate-tester.  Using 'compile 'com.google.android.gms:play-services-maps:9.0.1', everything works fine. Upgrading to 9.4.0 throws the java.lang.AbstractMethodError when compiling. What would be a possible way to fix this?

**Comment by mg6maciej** [comment] 2016-08-27 07:01
Hey,
This issue is fixed and waiting for me to merge it as part of pull request #40.
I'm currently on vacations and cannot release new version, so if you need the latest maps API, you can take source code, add it to your project and remove offending method `getExtendedMap`.

**Comment by mitjakoren** [comment] 2016-08-27 07:03
Thank you for the response @mg6maciej. Enjoy your vacation and thank you for pointing out the pull request. Best regards and looking forward to the next merged version.

**Comment by mg6maciej** [comment] 2016-09-29 15:51
This is now fixed in version 2.3.0. I have also added delegation for all features added recently in Google Maps Android API. Let me know if I missed something.

**Closed by mg6maciej** 2016-09-29 15:51 UTC

**Comment by df1994** [comment] 2016-11-03 13:18
Hi,
I did update to 2.3.0 but got RuntimeException:

> java.lang.RuntimeException: java.lang.NoSuchMethodException: getMap []
>                                                        at com.androidmapsextensions.MapHolder.getExtendedMap(MapHolder.java:39)

Any advice on that? Thanks!

**Comment by ultimate-tester** [comment] 2016-11-03 13:23
I think you need to use `getExtendedMapAsync` since versino 2.3.0.. At least that's what I understand from the pull request.

**Comment by df1994** [comment] 2016-11-03 13:24
Oh yes indeed, missed that one. Thanks!

**Comment by mg6maciej** [comment] 2016-11-03 14:35
You don't necessarily need to use `getExtendedMapAsync`, but if you update Google Maps Android API v2 to version 9.2 or newer, then you have to use that instead of `getExtendedMap`, because they removed `getMap` method from the original API.
